# Generated by Django 4.2 on 2026-01-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0002_teammember_successstory_resource_project_event_blog_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="successstory",
            name="image",
        ),
        migrations.AddField(
            model_name="successstory",
            name="image_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="image_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="image_url",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
