# Generated by Django 4.2 on 2026-01-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0004_faqs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="photo",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
