# Generated by Django 4.2 on 2026-01-31 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0005_alter_customuser_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="project",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="student_id",
            field=models.CharField(
                blank=True, help_text="Student ID e.g. 2002010001", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="demo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="domain",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("Ongoing", "Ongoing"), ("Completed", "Completed")],
                default="Ongoing",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="year",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["approval_status", "created_at"],
                name="admins_proj_approva_20f300_idx",
            ),
        ),
    ]
