# Generated by Django 4.2 on 2026-01-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0006_alter_project_options_project_approval_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="blog",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["approval_status", "created_at"],
                name="admins_blog_approva_3b348f_idx",
            ),
        ),
    ]
