# Generated by Django 4.2 on 2026-02-01 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0007_alter_blog_options_blog_approval_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resource",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="resource",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="resource",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="difficulty",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="resource",
            name="format",
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["approval_status", "created_at"],
                name="admins_reso_approva_2801d8_idx",
            ),
        ),
    ]
