# Generated by Django 4.2 on 2026-02-01 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0008_alter_resource_options_resource_approval_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="blog",
            options={},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.AlterModelOptions(
            name="resource",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="blog",
            name="admins_blog_approva_3b348f_idx",
        ),
        migrations.RemoveIndex(
            model_name="project",
            name="admins_proj_approva_20f300_idx",
        ),
        migrations.RemoveIndex(
            model_name="resource",
            name="admins_reso_approva_2801d8_idx",
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="customuser",
            name="student_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="blog",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="assigned_pages",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_users", to="admins.page"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("LAYERED_ADMIN", "Layered Admin"),
                    ("STUDENT", "Student"),
                ],
                default="STUDENT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="demo",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="domain",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="github",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.CharField(blank=True, default=" ", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("Ongoing", "Ongoing"), ("Completed", "Completed")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="student_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="year",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="resource",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="otp",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
