# Generated by Django 4.2 on 2026-02-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0009_otp_alter_blog_options_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="demo",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="github",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
