# Generated by Django 4.2 on 2026-02-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0010_alter_project_demo_alter_project_github_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("student_id", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=20)),
                ("hashed_password", models.CharField(max_length=128)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
