# Generated by Django 4.2 on 2026-02-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0011_pendingregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingregistration",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AddIndex(
            model_name="pendingregistration",
            index=models.Index(fields=["email"], name="admins_pend_email_25ec52_idx"),
        ),
        migrations.AddIndex(
            model_name="pendingregistration",
            index=models.Index(
                fields=["created_at"], name="admins_pend_created_818794_idx"
            ),
        ),
    ]
