# Generated by Django 4.2 on 2026-02-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0012_alter_pendingregistration_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("ADMIN", "Admin"),
                    ("LAYERED_ADMIN", "Layered Admin"),
                    ("STUDENT", "Student"),
                ],
                default="STUDENT",
                max_length=20,
            ),
        ),
    ]
