# Generated by Django 4.2 on 2026-02-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0014_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
