# Generated by Django 4.2 on 2026-02-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0015_alter_post_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="media",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of dicts: [{'type': 'image'|'video', 'url': '...', 'public_id': '...', ...}, ...]",
            ),
        ),
    ]
