# Generated by Django 4.2 on 2026-02-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0016_alter_post_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="media",
        ),
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.JSONField(
                blank=True, default=list, help_text="List of image URLs (strings)"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="videos",
            field=models.JSONField(
                blank=True, default=list, help_text="List of video URLs (strings)"
            ),
        ),
    ]
