# Generated by Django 4.2 on 2026-02-10 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0018_systemsetting_remove_customuser_assigned_pages_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alumni",
            options={"ordering": ["-created_at"]},
        ),
        
        migrations.AddField(
            model_name="alumni",
            name="about",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="alumni",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="alumni",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_alumni",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alumni",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alumni",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alumni",
            name="passing_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alumni",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="batch",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="company",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="session",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name="HistoricalAlumni",
        ),
    ]
