# Generated by Django 4.2 on 2026-02-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "admins",
            "0019_alter_alumni_options_rename_role_alumni_current_role_and_more",
        ),
    ]

    operations = [
        
    ]
