# Generated by Django 4.2 on 2026-02-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0020_rename_role_alumni_current_role_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alumni",
            old_name="role",
            new_name="current_role",
        ),
        migrations.RemoveField(
            model_name="alumni",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="alumni",
            name="year",
        ),
    ]
