# Generated by Django 4.2 on 2026-02-11 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0021_rename_role_alumni_current_role_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="committeemembership",
            options={"ordering": ["-year", "user__name"]},
        ),
        migrations.AlterModelOptions(
            name="teammember",
            options={"ordering": ["-year", "name"]},
        ),
        migrations.RemoveIndex(
            model_name="committeemembership",
            name="admins_comm_year_50aeca_idx",
        ),
    ]
